services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    command: ["postgres", "-c", "listen_addresses=*"]
  redis:
    image: redis
    command: redis-server
    volumes:
      - 'redis:/data'
  web:
    build: .
    command: ./bin/dev
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL_CACHING=redis://redis:6379/0
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    tty: true

volumes:
  redis:
  postgres: